# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Profile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Profile
    pod 'SnapKit'
  target 'ProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
