# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOSCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOSCare
    pod ‘SnapKit’
    pod 'SMIconLabel'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'MJSnackBar'
    pod 'EasyTipView', '~> 1.0.2'
    pod 'SwiftyJSON'
    pod 'SnapKit', '~> 4.0.0'

  target 'SOSCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOSCareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
