# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FundooNotes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FundooNotes
  #pod 'SwipeMenuViewController'
  pod 'XLActionController/Youtube'
  pod 'DatePickerDialog'
  pod 'UITextView+Placeholder'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'FundooNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FundooNotesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
